export default data =   [
      {
        "id": "0009",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-allouette.jpg'),
        "entite": "Alouette",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Avec plus de 457 000 auditeurs quotidiens, Alouette est la 2ème radio régionale de France . Alouette avec 43 fréquences réparties sur 15 départements et 4 régions couvre un grand arc Atlantique allant de Vannes à Bordeaux .Alouette se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Alouette comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Alouette séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication d’Alouette dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "PAYS-DE-LA-LOIRE",
        "departement": "Vendée",
        "code_postal": 85502,
        "ville": "LES HERBIERS",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0087",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-fg.jpg'),
        "entite": "FG",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Chaque jour se sont plus de 306 000 auditeurs qui écoutent Radio FG. Radio FG a été la première radio en France à dédier intégralement sa programmation à la musique électronique. Radio FG se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Radio FG comme une station musicale incontournable.",
        "region": "NC",
        "departement": "NC",
        "code_postal": "NC",
        "ville": "NC",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0088",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-fgl.jpg'),
        "entite": "FGL",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "FGL Fréquence Grands Lacs c’est 8 600 auditeurs chaque jour. FGL Fréquence Grands Lacs couvre le département des Landes avec 5 fréquences. FGL Fréquence Grands Lacs se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne FGL Fréquence Grands Lacs comme une station musicale incontournable dans les Landes. Autour d’un programme familial, consensuel et de proximité, FGL Fréquence Grands Lacs séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de FGL Fréquence Grands Lacs dans la vie locale (infos locales, création d’évènement) et par l’interactivité entre la station et ses auditeurs.",
        "region": "",
        "departement": "",
        "code_postal": 40601,
        "ville": "BISCARROSSE CÉDEX",
        "adresse": "Studios Diane Tell – 163 rue Jules Ferry – BP 30",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0089",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-forum.jpg'),
        "entite": "Forum",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Forum se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale à dominante Pop-Rock des hits des années 80 à 2000 positionne Forum comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Forum séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Forum dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "NC",
        "departement": "NC",
        "code_postal": "NC",
        "ville": "NC",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0091",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_hit-west.jpg'),
        "entite": "Hit West",
        "filiale_de": "Additi",
        "descriptif": "Hit West couvre l’ensemble de la Bretagne et une partie des Pays-de-la-Loire. Hit West se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Hit West comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Hit West séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication d’Hit West dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "PAYS-DE-LA-LOIRE",
        "departement": "Loire-Atlantique",
        "code_postal": 44200,
        "ville": "NANTES",
        "adresse": "2, quai François Mitterrand",
        "latitude": 47.2071,
        "longitude": -1.55559,
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      }
      // {
      //   "id": "0100",
      //   "ident_visuel": require('../assets/images/sipa/publihebdos/normandie/logo-500x172_l-eclaireur-de-gamaches.jpg'),
      //   "entite": "L’Éclaireur de Gamache",
      //   "filiale_de": "Publihebdos",
      //   "descriptif": "Hebdomadaire, parution le mardi – Audience : 20250 lecteurs",
      //   "region": "NORMANDIE",
      //   "departement": "Seine-Maritime",
      //   "code_postal": 76260,
      //   "ville": "EU",
      //   "adresse": "1, place Saint-Jacques",
      //   "latitude": "",
      //   "longitude": "",
      //   "type_lieu": "Rédaction",
      //   "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
      //   "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
      //   "dirigeant1": "Dominique DELANNOY",
      //   "poste1": "Rédacteur en Chef",
      //   "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
      //   "dirigeant2": "Francis GAUNAND",
      //   "poste2": "Directeur de la publication",
      //   "site": "",
      //   "telephone": "02 35 86 07 11",
      //   "email": "eclaireur-gamaches@publihebdos.fr"
      // },


  ]