export default data =   [
      {
        "id": "0009",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-allouette.jpg'),
        "entite": "Alouette",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Avec plus de 457 000 auditeurs quotidiens, Alouette est la 2ème radio régionale de France . Alouette avec 43 fréquences réparties sur 15 départements et 4 régions couvre un grand arc Atlantique allant de Vannes à Bordeaux .Alouette se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Alouette comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Alouette séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication d’Alouette dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "PAYS-DE-LA-LOIRE",
        "departement": "Vendée",
        "code_postal": 85502,
        "ville": "LES HERBIERS",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0087",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-fg.jpg'),
        "entite": "FG",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Chaque jour se sont plus de 306 000 auditeurs qui écoutent Radio FG. Radio FG a été la première radio en France à dédier intégralement sa programmation à la musique électronique. Radio FG se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Radio FG comme une station musicale incontournable.",
        "region": "NC",
        "departement": "NC",
        "code_postal": "NC",
        "ville": "NC",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0088",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-fgl.jpg'),
        "entite": "FGL",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "FGL Fréquence Grands Lacs c’est 8 600 auditeurs chaque jour. FGL Fréquence Grands Lacs couvre le département des Landes avec 5 fréquences. FGL Fréquence Grands Lacs se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne FGL Fréquence Grands Lacs comme une station musicale incontournable dans les Landes. Autour d’un programme familial, consensuel et de proximité, FGL Fréquence Grands Lacs séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de FGL Fréquence Grands Lacs dans la vie locale (infos locales, création d’évènement) et par l’interactivité entre la station et ses auditeurs.",
        "region": "",
        "departement": "",
        "code_postal": 40601,
        "ville": "BISCARROSSE CÉDEX",
        "adresse": "Studios Diane Tell – 163 rue Jules Ferry – BP 30",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0089",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-forum.jpg'),
        "entite": "Forum",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Forum se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale à dominante Pop-Rock des hits des années 80 à 2000 positionne Forum comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Forum séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Forum dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "NC",
        "departement": "NC",
        "code_postal": "NC",
        "ville": "NC",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0091",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_hit-west.jpg'),
        "entite": "Hit West",
        "filiale_de": "Additi",
        "descriptif": "Hit West couvre l’ensemble de la Bretagne et une partie des Pays-de-la-Loire. Hit West se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Hit West comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Hit West séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication d’Hit West dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "PAYS-DE-LA-LOIRE",
        "departement": "Loire-Atlantique",
        "code_postal": 44200,
        "ville": "NANTES",
        "adresse": "2, quai François Mitterrand",
        "latitude": 47.2071,
        "longitude": -1.55559,
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0013",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_contact-fm.jpg'),
        "entite": "Contact FM",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Contact FM c’est plus de 303 000 auditeurs chaque jour. Contact FM couvre 6 départements avec 22 fréquences dans les Hauts-de-France. Contact FM se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Hit West comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Contact FM séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Contact FM dans la vie locale (infos locales, création d’évènement) et par l’interactivité entre la station et ses auditeurs.",
        "region": "",
        "departement": "",
        "code_postal": 59000,
        "ville": "LILLE",
        "adresse": "8, place du Général De Gaulle",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0165",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-mti.jpg'),
        "entite": "MTI",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "MTI c’est plus de  42 000 auditeurs chaque jour. MTI est présent dans 3 départements : la Drôme, l’Ardèche et le Gard. Ses émetteurs lui permettent également de couvrir le Nord Ouest du département du Vaucluse. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne MTI comme une station musicale incontournable sur ces départements. Ainsi, MTI se positionne comme une radio musicale de divertissement et de proximité. Enfin, cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de MTI dans la vie locale (infos locales, création d’évènement) et par l’interactivité entre la station et ses auditeurs.",
        "region": "BRETAGNE",
        "departement": "Ille-et-Vilaine",
        "code_postal": 35200,
        "ville": "RENNES",
        "adresse": "16, avenue Henri Fréville",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0166",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_oceane-fm.jpg'),
        "entite": "Océane FM",
        "filiale_de": "Additi",
        "descriptif": "Océane FM se positionne comme une radio musicale de divertissement et de proximité. Par sa programmation musicale, Océane FM est une radio qui s’adresse principalement aux auditeurs de 35 ans ou plus. Autour d’un programme familial, consensuel et de proximité, Océane FM séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de d’Océane FM dans la vie locale (infos locales, agendas et sorties) et par l’interactivité entre la station et ses auditeurs.",
        "region": "BRETAGNE",
        "departement": "NC",
        "code_postal": 56230,
        "ville": "Questembert",
        "adresse": "4, rue Jérôme de Carné",
        "latitude": 47.6611,
        "longitude": -2.4542,
        "type_lieu": "NC",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0178",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-bonheur.jpg'),
        "entite": "Radio Bonheur",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Présent sur les Côtes-d’Armor, le Centre Bretagne et la région malouine, Radio Bonheur est LA station qui diffuse exclusivement des chansons Françaises. Le programme musical de Radio Bonheur est clairement un format musical ciblant les adultes et les séniors. Autour d’un programme familial, consensuel et de proximité, Radio Bonheur séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de de Radio Bonheur dans la vie locale (infos locales, météo marine, agendas et sorties) et par l’interactivité entre la station et ses auditeurs notamment en donnant quotidiennement la parole à plus de 1 200 associations. Enfin cette proximité s’exprime également à travers la retransmission des matchs de l’En Avant Guingamp.",
        "region": "BRETAGNE",
        "departement": "Côtes d’Armor",
        "code_postal": 22370,
        "ville": "PLÉNEUF-VAL-ANDRÉ",
        "adresse": "6, rue de Saint-Alban",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0179",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-cristal.jpg'),
        "entite": "Radio Cristal",
        "filiale_de": "Additi",
        "descriptif": "Radio Cristal se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne Radio Cristal comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, Radio Cristal séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Radio Cristal dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "NORMANDIE",
        "departement": "Calvados",
        "code_postal": 14610,
        "ville": "EPRON",
        "adresse": "Bâtiment Précom, route de Caen",
        "latitude": 49.22017,
        "longitude": -0.36657,
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0180",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-flash.jpg'),
        "entite": "Radio Flash",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Radio Flash, c’est 2 fréquence en Cévennes Méditerranée qui réunissent 51 400 auditeurs chaque semaine. Radio Flash se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment.Autour d’un programme familial, consensuel et de proximité, Radio Flash séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Radio Flash dans la vie locale (infos locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "",
        "departement": "",
        "code_postal": 34270,
        "ville": "VALFLAUNÈS",
        "adresse": "rue d'Alicante",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0181",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-ocean.jpg'),
        "entite": "Radio Océan",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "RadiOcéan est actuellement implanté dans 2 départements :   Le Finistère : 68 100 auditeurs chaque semaine, lLe Morbihan : 50 300 auditeurs chaque semaine. RadiOcéan se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits des années 60 à nos jours. Autour d’un programme familial, consensuel et de proximité, RadiOcéan séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de RadiOcéan dans la vie locale (infos locales, création d’évènement) et par l’interactivité entre la station et ses auditeurs.",
        "region": "",
        "departement": "",
        "code_postal": "",
        "ville": "MOËLAN-SUR-MER",
        "adresse": "",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0182",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-vfm.jpg'),
        "entite": "Radio VFM",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Radio VFM présente sur une partie du Calvados réunit chaque semaine plus de 24 000 auditeurs. VFM est ainsi la 1ère des radios locales sur la zone de Vire-Bayeux. VFM se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constitué des principaux hits du moment positionne VFM comme une station musicale incontournable. Autour d’un programme familial, consensuel et de proximité, VFM séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de VFM dans la vie locale (infos locales, météo locale, agendas et sorties) et par l’interactivité entre la station et ses auditeurs.",
        "region": "NC",
        "departement": "NC",
        "code_postal": "NC",
        "ville": "NC",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0183",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-rba.jpg'),
        "entite": "RBA",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "RBA – Radio Bassin d’Arcachon c’est 6 500 auditeurs chaque jour. RBA – Radio Bassin d’Arcachon couvre l’ensemble du Bassin d’Arcachon. RBA – Radio Bassin d’Arcachon se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits du moment positionne RBA – Radio Bassin d’Arcachon comme une station musicale incontournable du Bassin d’Arcachon. Autour d’un programme familial, consensuel et de proximité, RBA – Radio Bassin d’Arcachon séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de RBA – Radio Bassin d’Arcachon dans la vie locale (infos locales, création d’évènement) et par l’interactivité entre la station et ses auditeurs.",
        "region": "BRETAGNE",
        "departement": "Ille-et-Vilaine",
        "code_postal": 35200,
        "ville": "RENNES",
        "adresse": "17, avenue Henri Fréville",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0200",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-rfm.jpg'),
        "entite": "RFM",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "La station de la famille offre une programmation riche et diversifiée à ses auditeurs, qui sont de plus en plus nombreux ! Pop music, disco, funk, rock et nouveautés font les couleurs de la station, avec des artistes emblématiques, telle est la recette du meilleur de la musique ! RFM c’est aussi de la bonne humeur avec dès 6h « Le Meilleur des Réveils » désormais animé par Elodie GOSSUIN et Albert SPANO et rassemble tous les matins plus d’1,1 million d’auditeurs fidèles. RFM c’est également des interviews inédites menées par Karine FERRI le week-end. Chez vous, en voiture, au travail ou sur votre mobile, désormais le meilleur de la musique est accessible partout et à tout moment.",
        "region": "BRETAGNE",
        "departement": "Ille-et-Vilaine",
        "code_postal": 35081,
        "ville": "RENNES",
        "adresse": "16, avenue Henri Fréville",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0201",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-sea-fm.jpg'),
        "entite": "Sea FM",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Chaque semaine, plus de 48 000 personnes écoutent Sea FM sur le département de la Manche. Sea FM se positionne comme une radio musicale de divertissement et de proximité avec une programmation musicale généraliste destiné au plus de 35 ans. Autour d’un programme familial, consensuel et de proximité, Sea FM séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Sea FM dans la vie locale (infos locales, agendas et sorties) et par l’interactivité entre la station et ses auditeurs.",
        "region": "BRETAGNE",
        "departement": "Ille-et-Vilaine",
        "code_postal": 35200,
        "ville": "RENNES",
        "adresse": "10, rue du Breil - ZI Chantepie",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "Patrick LELIÈVRE",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "Christian PHILLIBERT",
        "poste2": "NC",
        "site": "http://www.seafm.fr",
        "telephone": "02 33 19 03 09",
        "email": ""
      },
      {
        "id": "0205",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-sweet-fm.jpg'),
        "entite": "Sweet FM",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Fortement implanté sur son territoire, Sweet FM touche également 30% des habitants du Perche. Avec son format généraliste, Sweet FM attire un large public tout au long de la journée. La matinale est très rythmée et axée sur l’information ; tandis que la soirée est plus musicale et interactive afin de capter un auditoire plus jeune. Autour d’un programme familial, consensuel et de proximité, Sweet FM séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Sweet FM dans la vie locale (infos et météo locales, création d’évènement et de concert) et par l’interactivité entre la station et ses auditeurs.",
        "region": "PAYS-DE-LA-LOIRE",
        "departement": "Sarthe",
        "code_postal": 72000,
        "ville": "LE MANS",
        "adresse": "25, rue des Marais",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0207",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-vibration.jpg'),
        "entite": "Vibration",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Vibration se positionne comme une radio musicale de divertissement et de proximité. Le choix d’une programmation musicale généraliste et constituée des principaux hits français et internationaux Vibration comme une station musicale incontournable.Autour d’un programme familial, consensuel et de proximité, Vibration séduit un très large public. Cette proximité avec les auditeurs s’est construite autour de 2 axes : l’implication de Vibration dans la vie locale (infos locales, agendas et sorties) et par l’interactivité entre la station et ses auditeurs.",
        "region": "NC",
        "departement": "NC",
        "code_postal": "NC",
        "ville": "NC",
        "adresse": "NC",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      {
        "id": "0219",
        "ident_visuel": require('../assets/images/sipa/additi/regie-radios-regions/logo-500x172_radio-virgin.jpg'),
        "entite": "Virgin Radio",
        "filiale_de": "Radios Régie Régions",
        "descriptif": "Installé dans son format musical unique Pop Rock Electro, Virgin Radio est devenu une référence grâce à une playlist qui mixe références et nouveaux talents du genre. Virgin Radio sait aussi révéler les talents et dénicher les incontournables de la scène musicale française de demain. De la bonne humeur & de la complicité autour de la matinale Virgin Tonic animée par Camille Combal tous les matins de 7h à 10h et totalise près de 1,4 million d’auditeurs chaque matin.",
        "region": "ÎLE-DE-FRANCE",
        "departement": "Paris",
        "code_postal": 75015,
        "ville": "PARIS",
        "adresse": "2, rue des Cévennes",
        "latitude": "",
        "longitude": "",
        "type_lieu": "Siège",
        "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
        "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant1": "NC",
        "poste1": "NC",
        "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
        "dirigeant2": "NC",
        "poste2": "NC",
        "site": "",
        "telephone": "",
        "email": ""
      },
      // {
      //   "id": "0100",
      //   "ident_visuel": require('../assets/images/sipa/publihebdos/normandie/logo-500x172_l-eclaireur-de-gamaches.jpg'),
      //   "entite": "L’Éclaireur de Gamache",
      //   "filiale_de": "Publihebdos",
      //   "descriptif": "Hebdomadaire, parution le mardi – Audience : 20250 lecteurs",
      //   "region": "NORMANDIE",
      //   "departement": "Seine-Maritime",
      //   "code_postal": 76260,
      //   "ville": "EU",
      //   "adresse": "1, place Saint-Jacques",
      //   "latitude": "",
      //   "longitude": "",
      //   "type_lieu": "Rédaction",
      //   "photo_lieu": require('../assets/images/gen/png/photo-lieu-defaut.png'),
      //   "ident_dirigeant1":  require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
      //   "dirigeant1": "Dominique DELANNOY",
      //   "poste1": "Rédacteur en Chef",
      //   "ident_dirigeant2" : require('../assets/images/gen/png/ident-dirigeant-defaut.png'),
      //   "dirigeant2": "Francis GAUNAND",
      //   "poste2": "Directeur de la publication",
      //   "site": "",
      //   "telephone": "02 35 86 07 11",
      //   "email": "eclaireur-gamaches@publihebdos.fr"
      // },


  ]